# Data Prep

In [36]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
import matplotlib.pyplot as plt
import pybaseball as pb

In [37]:
df = pd.read_csv('statcast_2023_2025.csv')

In [38]:
df.description.unique()

array(['hit_into_play', 'called_strike', 'foul', 'swinging_strike',
       'ball', 'foul_tip', 'blocked_ball', 'swinging_strike_blocked',
       'hit_by_pitch', 'foul_bunt', 'automatic_strike', 'automatic_ball',
       'missed_bunt', 'bunt_foul_tip', 'pitchout'], dtype=object)

In [39]:
at_bat_map = {'field_out':1, 'strikeout':1, np.nan:0, 'single':1, 'walk':0,
                'grounded_into_double_play':1, 'double':1, 'home_run':1, 'force_out':1,
                'hit_by_pitch':0, 'triple':1, 'sac_fly':0, 'sac_bunt':0, 'field_error':1,
                'fielders_choice_out':1, 'intent_walk':0, 'fielders_choice':1,
                'double_play':1, 'strikeout_double_play':1, 'truncated_pa':0,
                'sac_fly_double_play':0, 'catcher_interf':0, 'triple_play':1}

pa_map = {'field_out':1, 'strikeout':1, np.nan:0, 'single':1, 'walk':1,
       'grounded_into_double_play':1, 'double':1, 'home_run':1, 'force_out':1,
       'hit_by_pitch':1, 'triple':1, 'sac_fly':1, 'sac_bunt':0, 'field_error':1,
       'fielders_choice_out':1, 'intent_walk':1, 'fielders_choice':1,
       'double_play':1, 'strikeout_double_play':1, 'truncated_pa':0,
       'sac_fly_double_play':1, 'catcher_interf':1, 'triple_play':1}

swing_map = {'hit_into_play':1, 'called_strike':0, 'foul':1, 'swinging_strike':1,
       'ball':0, 'foul_tip':1, 'blocked_ball':0, 'swinging_strike_blocked':1,
       'hit_by_pitch':0, 'foul_bunt':1, 'automatic_strike':0, 'automatic_ball':0,
       'missed_bunt':1, 'bunt_foul_tip':1, 'pitchout':0}

contact_map = {'hit_into_play':1, 'called_strike':0, 'foul':1, 'swinging_strike':0,
       'ball':0, 'foul_tip':1, 'blocked_ball':0, 'swinging_strike_blocked':0,
       'hit_by_pitch':0, 'foul_bunt':1, 'automatic_strike':0, 'automatic_ball':0,
       'missed_bunt':0, 'bunt_foul_tip':1, 'pitchout':0}

batted_ball_map = {'hit_into_play':1, 'called_strike':0, 'foul':0, 'swinging_strike':0,
       'ball':0, 'foul_tip':0, 'blocked_ball':0, 'swinging_strike_blocked':0,
       'hit_by_pitch':0, 'foul_bunt':0, 'automatic_strike':0, 'automatic_ball':0,
       'missed_bunt':0, 'bunt_foul_tip':0, 'pitchout':0}

k_map = {'field_out':0, 'strikeout':1, np.nan:0, 'single':0, 'walk':0,
       'grounded_into_double_play':0, 'double':0, 'home_run':0, 'force_out':0,
       'hit_by_pitch':0, 'triple':0, 'sac_fly':0, 'sac_bunt':0, 'field_error':0,
       'fielders_choice_out':0, 'intent_walk':0, 'fielders_choice':0,
       'double_play':0, 'strikeout_double_play':1, 'truncated_pa':0,
       'sac_fly_double_play':0, 'catcher_interf':0, 'triple_play':0}

bb_map = {'field_out':0, 'strikeout':0, np.nan:0, 'single':0, 'walk':1,
       'grounded_into_double_play':0, 'double':0, 'home_run':0, 'force_out':0,
       'hit_by_pitch':0, 'triple':0, 'sac_fly':0, 'sac_bunt':0, 'field_error':0,
       'fielders_choice_out':0, 'intent_walk':1, 'fielders_choice':0,
       'double_play':0, 'strikeout_double_play':0, 'truncated_pa':0,
       'sac_fly_double_play':0, 'catcher_interf':0, 'triple_play':0}

ibb_map = {'field_out':0, 'strikeout':0, np.nan:0, 'single':0, 'walk':0,
       'grounded_into_double_play':0, 'double':0, 'home_run':0, 'force_out':0,
       'hit_by_pitch':0, 'triple':0, 'sac_fly':0, 'sac_bunt':0, 'field_error':0,
       'fielders_choice_out':0, 'intent_walk':1, 'fielders_choice':0,
       'double_play':0, 'strikeout_double_play':0, 'truncated_pa':0,
       'sac_fly_double_play':0, 'catcher_interf':0, 'triple_play':0}

hbp_map = {'field_out':0, 'strikeout':0, np.nan:0, 'single':0, 'walk':0,
       'grounded_into_double_play':0, 'double':0, 'home_run':0, 'force_out':0,
       'hit_by_pitch':1, 'triple':0, 'sac_fly':0, 'sac_bunt':0, 'field_error':0,
       'fielders_choice_out':0, 'intent_walk':0, 'fielders_choice':0,
       'double_play':0, 'strikeout_double_play':0, 'truncated_pa':0,
       'sac_fly_double_play':0, 'catcher_interf':0, 'triple_play':0}

b1_map = {'field_out':0, 'strikeout':0, np.nan:0, 'single':1, 'walk':0,
       'grounded_into_double_play':0, 'double':0, 'home_run':0, 'force_out':0,
       'hit_by_pitch':0, 'triple':0, 'sac_fly':0, 'sac_bunt':0, 'field_error':0,
       'fielders_choice_out':0, 'intent_walk':0, 'fielders_choice':0,
       'double_play':0, 'strikeout_double_play':0, 'truncated_pa':0,
       'sac_fly_double_play':0, 'catcher_interf':0, 'triple_play':0}

b2_map = {'field_out':0, 'strikeout':0, np.nan:0, 'single':0, 'walk':0,
       'grounded_into_double_play':0, 'double':1, 'home_run':0, 'force_out':0,
       'hit_by_pitch':0, 'triple':0, 'sac_fly':0, 'sac_bunt':0, 'field_error':0,
       'fielders_choice_out':0, 'intent_walk':0, 'fielders_choice':0,
       'double_play':0, 'strikeout_double_play':0, 'truncated_pa':0,
       'sac_fly_double_play':0, 'catcher_interf':0, 'triple_play':0}

b3_map = {'field_out':0, 'strikeout':0, np.nan:0, 'single':0, 'walk':0,
       'grounded_into_double_play':0, 'double':0, 'home_run':0, 'force_out':0,
       'hit_by_pitch':0, 'triple':1, 'sac_fly':0, 'sac_bunt':0, 'field_error':0,
       'fielders_choice_out':0, 'intent_walk':0, 'fielders_choice':0,
       'double_play':0, 'strikeout_double_play':0, 'truncated_pa':0,
       'sac_fly_double_play':0, 'catcher_interf':0, 'triple_play':0}

hr_map = {'field_out':0, 'strikeout':0, np.nan:0, 'single':0, 'walk':0,
       'grounded_into_double_play':0, 'double':0, 'home_run':1, 'force_out':0,
       'hit_by_pitch':0, 'triple':0, 'sac_fly':0, 'sac_bunt':0, 'field_error':0,
       'fielders_choice_out':0, 'intent_walk':0, 'fielders_choice':0,
       'double_play':0, 'strikeout_double_play':0, 'truncated_pa':0,
       'sac_fly_double_play':0, 'catcher_interf':0, 'triple_play':0}

sf_map = {'field_out':0, 'strikeout':0, np.nan:0, 'single':0, 'walk':0,
       'grounded_into_double_play':0, 'double':0, 'home_run':0, 'force_out':0,
       'hit_by_pitch':0, 'triple':0, 'sac_fly':1, 'sac_bunt':0, 'field_error':0,
       'fielders_choice_out':0, 'intent_walk':0, 'fielders_choice':0,
       'double_play':0, 'strikeout_double_play':0, 'truncated_pa':0,
       'sac_fly_double_play':1, 'catcher_interf':0, 'triple_play':0}

zone_map = {1:1, 2:1, 3:1, 4:1, 5:1, 6:1, 7:1, 8:1, 9:1, 11:0, 12:0, 13:0, 14:0}

In [40]:
df['at_bat'] = df['events'].map(at_bat_map)
df['is_swing'] = df['description'].map(swing_map)
df['contact'] = df['description'].map(contact_map)
df['batted_ball'] = df['description'].map(batted_ball_map)
df['in_zone'] = df['zone'].map(zone_map)
df['plate_appearance'] = df['events'].map(pa_map)
df['is_barrel'] = (df['launch_speed_angle'] == 6)
df['bb'] = df['events'].map(bb_map)
df['k'] = df['events'].map(k_map)
df['is_hard_hit'] = (df['launch_speed'] >= 95)
df['hbp'] = df['events'].map(hbp_map)
df['single'] = df['events'].map(b1_map)
df['double'] = df['events'].map(b2_map)
df['triple'] = df['events'].map(b3_map)
df['hr'] = df['events'].map(hr_map)
df['sf'] = df['events'].map(sf_map)
df['ibb'] = df['events'].map(ibb_map)

In [41]:
o_swing = df.loc[df.in_zone == 0].groupby(['batter','season'], as_index = False).agg({'is_swing':'mean'})
hh_rate = df.loc[df.batted_ball == 1].groupby(['batter','season'], as_index = False).agg({'is_hard_hit':'mean'})
z_swing = df.loc[df.in_zone == 1].groupby(['batter','season'], as_index = False).agg({'is_swing':'mean'})
barrell = df.loc[df.batted_ball == 1].groupby(['batter','season'], as_index = False).agg({'is_barrel':'mean'})
at_bats = df.groupby(['batter','season'], as_index = False).agg({'at_bat':'sum'})
contact_rate = df.loc[df.is_swing == 1].groupby(['batter','season'], as_index = False).agg({'contact':'mean'})
k_rate = df.loc[df.plate_appearance == 1].groupby(['batter','season'], as_index = False).agg({'k':'mean'})
bb_rate = df.loc[df.plate_appearance == 1].groupby(['batter','season'], as_index = False).agg({'bb':'mean'})
cross_plate = df.groupby(['batter','season'], as_index = False).agg({'intercept_ball_minus_batter_pos_y_inches':'mean'})

In [42]:
woba = df.groupby(['batter','season'], as_index = False).agg({'bb':'sum','hbp':'sum','single':'sum','double':'sum','triple':'sum','hr':'sum','at_bat':'sum',
                                                        'sf':'sum','ibb':'sum'})
woba['woba'] = (0.69*(woba.bb-woba.ibb) + 0.72*woba.hbp + 0.88*woba.single + 1.25*woba.double + 1.58*woba.triple + 2.01*woba.hr) / (woba.at_bat + woba.bb - woba.ibb + woba.sf + woba.hbp)

In [43]:
df = o_swing.merge(z_swing, on = ['batter','season'])
df = df.merge(barrell, on = ['batter','season'])
df = df.merge(woba[['batter','season','woba']], on = ['batter','season'])
df = df.merge(at_bats, on = ['batter','season'])
df = df.merge(contact_rate, on = ['batter', 'season'])
df = df.merge(k_rate, on = ['batter', 'season'])
df = df.merge(bb_rate, on = ['batter', 'season'])
df = df.merge(hh_rate, on = ['batter', 'season'])
df = df.merge(cross_plate, on = ['batter', 'season'])

df.columns = ['batter','season','o-swing%','z-swing%','barrel%','woba','at_bats','contact%','K%','BB%','hard_hit%','intercept_ball_minus_batter_pos_y_inches']

In [44]:
df['next_season'] = df['season'] + 1

In [45]:
df = df.loc[df.at_bats >= df.at_bats.max()/3]

In [46]:
df = df.merge(df[['batter','season','woba']], left_on = ['batter','next_season'], right_on = ['batter','season'], how = 'left')

# Modelling

In [122]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error

In [123]:
df1 = df.loc[df.season_x.isin([2023, 2024])]
df1 = df1.dropna()
df2 = df.loc[df.season_x == 2025]

In [124]:
features = ['o-swing%', 'z-swing%', 'barrel%', 'contact%', 'hard_hit%', 'intercept_ball_minus_batter_pos_y_inches','woba_x']

In [125]:
X = df1[features]
y = df1['woba_y']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.01,
    random_state=42,
    shuffle=True
)

In [126]:
model = XGBRegressor(
    n_estimators=300,
    max_depth=8,
    learning_rate=0.01,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42
)

model.fit(X_train, y_train)
preds = model.predict(X_test)

rmse = mean_squared_error(y_test, preds) ** 0.5
print("RMSE:", rmse)

RMSE: 0.02960124649827948

In [127]:
preds_26 = model.predict(df2[features])

In [128]:
df2['xWOBA_2026'] = preds_26

C:\Users\murph\AppData\Local\Temp\ipykernel_10752\4225032295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['xWOBA_2026'] = preds_26

In [129]:
seasons = [2023, 2024, 2025]
df_names = []
for s in seasons:
    velo = pb.statcast_batter_exitvelo_barrels(s)
    velo['season'] = s
    df_names.append(velo)

In [130]:
df_names = pd.concat(df_names)
df_names = df_names.drop_duplicates('player_id')

In [131]:
df_names.head()

,"last_name, first_name",player_id,attempts,avg_hit_angle,anglesweetspotpercent,max_hit_speed,avg_hit_speed,ev50,fbld,gb,max_distance,avg_distance,avg_hr_distance,ev95plus,ev95percent,barrels,brl_percent,brl_pa,season
0,"Kwan, Steven",680757,570,10.7,37.4,105.2,86.0,94.1,87.6,85.2,407,149,386.0,107,18.8,6,1.1,0.8,2023
1,"Semien, Marcus",543760,565,19.1,37.5,108.6,88.4,98.1,91.2,85.2,433,194,393.0,209,37.0,37,6.5,4.9,2023
2,"Acuña Jr., Ronald",660670,562,7.4,33.6,121.2,94.7,106.4,98.4,91.6,470,162,420.0,310,55.2,86,15.3,11.7,2023
3,"Arraez, Luis",650333,544,11.5,44.7,104.0,88.3,95.7,90.4,85.8,410,168,381.0,140,25.7,19,3.5,3.1,2023
4,"Ramírez, José",608070,544,18.0,36.8,111.6,90.0,100.1,92.2,90.6,431,179,402.0,220,40.4,38,7.0,5.5,2023

In [132]:
df2 = df2.merge(df_names[['player_id','last_name, first_name']], left_on = 'batter', right_on = 'player_id', how = 'left')

In [133]:
df2.head()

,batter,season_x,o-swing%,z-swing%,barrel%,woba_x,at_bats,contact%,K%,BB%,hard_hit%,intercept_ball_minus_batter_pos_y_inches,next_season,season_y,woba_y,xWOBA_2026,player_id,"last_name, first_name"
0,457705,2025,0.207084,0.690395,0.082873,0.307665,477,0.757018,0.214156,0.121597,0.425414,24.806338,2026,NaN,NaN,0.322097,457705.0,"McCutchen, Andrew"
1,467793,2025,0.247515,0.659465,0.048780,0.283150,415,0.775281,0.191983,0.109705,0.378049,33.353410,2026,NaN,NaN,0.295710,467793.0,"Santana, Carlos"
2,500743,2025,0.267581,0.631218,0.040486,0.310927,290,0.835878,0.146497,0.076433,0.311741,34.141386,2026,NaN,NaN,0.300391,500743.0,"Rojas, Miguel"
3,502054,2025,0.198667,0.606695,0.066007,0.306368,392,0.794239,0.209354,0.111359,0.471947,31.752985,2026,NaN,NaN,0.310111,502054.0,"Pham, Tommy"
4,502671,2025,0.273367,0.662716,0.079284,0.314943,489,0.816817,0.187266,0.067416,0.437340,20.342615,2026,NaN,NaN,0.326644,502671.0,"Goldschmidt, Paul"

In [134]:
woba = df2[['player_id','batter','last_name, first_name','woba_x', 'xWOBA_2026']].sort_values(by = 'xWOBA_2026', ascending = False)

In [135]:
woba['x_diff'] = woba['xWOBA_2026'] - woba['woba_x']

In [138]:
woba.dropna().sort_values(by = 'x_diff', ascending = False).head(10)

     player_id  batter last_name, first_name    woba_x  xWOBA_2026    x_diff
233   681351.0  681351        O'Hoppe, Logan  0.271844    0.325723  0.053879
176   669397.0  669397           Allen, Nick  0.244559    0.297940  0.053381
172   669289.0  669289     Espinal, Santiago  0.258123    0.308066  0.049943
185   670764.0  670764         Walls, Taylor  0.264013    0.312638  0.048625
138   665833.0  665833           Cruz, Oneil  0.293259    0.340692  0.047432
291   696285.0  696285          Young, Jacob  0.263239    0.304905  0.041665
18    553869.0  553869           Díaz, Elias  0.267806    0.304771  0.036966
72    641680.0  641680           Heim, Jonah  0.264653    0.301107  0.036454
144   666134.0  666134          Jones, Nolan  0.269451    0.305089  0.035638
115   663647.0  663647       Hayes, Ke'Bryan  0.265035    0.298827  0.033792